version: '3.8'
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    env_file:
      - ./redis.env

  memcached:
    image: memcached:latest
    restart: always
    ports:
      - 11211:11211
    env_file:
      - ./memcached.env

  riak:
    image: basho/riak-kv:latest
    restart: always
    ports:
      - 8087:8087
      - 8098:8098